name=input("enter name:")
age=int(input("enter age:"))
print(f"My age is {age} and my name is {name}.")
print("My name is",name,"and my age is",age,".")
print("Hello my name is" +name+ "and i am" +str(age) +"years old")
print("Hello my name is %s and i am % d years old" %(name,age))
print("Hello my name is {} and i am {} years old".format(name,age))
